contentDir = "content/zh-tw"
languageName = "中文"

# Menu
about = "About Us"
history = "History"
activity = "Activity"
faculty = "Faculty"
place = "Exhibition Venue"
collect_music = "NTHU Chamber Ensemble"
collect_art = "NTHU Art Salon"
programs = "Programs"
public_art = "Public Art"
visual_art = "Visual Art"
performing_art = "Performing Art"
film_art = "Film Art"
ai_music = "AI Music"
publication = "Publication"
posts = "Column"
friends = "Friends"
calendar = "Calendar"

# Footer
footer_open_time = "諮詢時間"
footer_phone = "電話"
footer_fax = "傳真"
footer_email = "電子信箱"
footer_address = "地址"
footer_maintainer = "網站維護"
footer_open_time_content = "周一至周五 9:00-12:00；14:00-17:00"
footer_phone_content = "886-3-5162222"
footer_fax_content = "886-3-5726819"
footer_email_content = "arts@my.nthu.edu.tw"
footer_address_content = "30013新竹市光復路二段101號綜合大樓二館1樓"
footer_calender = "活動月曆"
footer_zyxel = "日治時期"
footer_exhibition_hall = "藝術中心展覽廳"
footer_art_workshop = "臺北市轄"
footer_application_for_exhibition = "展演申請"
footer_seeking = "競賽徵件"
footer_sponsor = "贊助藝中"
footer_volunteer = "志工招募"
footer_school = "國立清華大學"
footer_museum = "國立故宮博物院"
footer_theater = "國家兩廳院"
footer_taichung_theater = "國家歌劇院"

# Footer mobile
footer_mobile_open_time = "諮詢時間: 周一至周五 9:00-12:00；14:00-17:00"
footer_mobile_phone = "電話：886-3-5162222"
footer_mobile_fax = "傳真：886-3-5726819"
footer_mobile_email = "電子信箱：arts@my.nthu.edu.tw"
footer_mobile_address = "地址：30013新竹市光復路二段101號綜合大樓二館1樓"

# Event tag
tag_public_art = "籌備會議"
tag_visual_art = "行政會議"
tag_performing_art = "場地整修"
tag_film_art = "活動練習"
tag_ai_music = "預演彩排"
tag_2020spring = "2020春"
tag_2019fall = "2019秋"
tag_2019spring = "2019春"
tag_2018fall = "2018秋"
tag_2018spring = "2018春"

# Event Detail
ed_information = "展演資訊"
ed_host = "主辦"
ed_performer = "展演者"
ed_time = "時間"
ed_location = "地點"
ed_ticket_info = "售票資訊"
ed_registration_link = "報名連結"
ed_exhibition_images = "展覽圖片"
ed_detail = "展演介紹"

[page_index]
upcoming_event = "近期活動"
latest_news = "最新消息"

[page_history]
p1 = "本校於1988年成立清大藝術中心，為提升大學校園藝術氣息，培育人文、藝術與科學優秀人才，孕育深具社會功能與文化意涵的展演搖籃，此舉為全國大學藝術中心之首創。自此以往，藝術中心成為校園和社區文化藝術生活的中心，在校園中擔任活絡藝文氣息的重要角色，負責籌辦藝術展演、推廣美術教育與活動、提昇藝文欣賞能力，協助美化校園空間。"
p2 = "藝術中心自成立以來朝著多元性、全方位的藝術活動面向發展，不僅是校園實質的藝術機構，服務對象涵蓋師長、青年學子乃至新竹眾多社區民眾，帶動周邊藝文產業的 發展，使藝術家們能在新竹縣市地區有展演的機會，不論是視覺、音樂、表演、電影 藝術均努力不懈地詮釋當代藝術風貌，提供校園師生社區民眾與當代藝術家們面對面 互動之機會，創造優良藝術環境與氛圍，樹立鮮明的藝術形象與良好的口碑，培養師 生藝術感知能力，落實美感教育。"
p3 = "行政會議是眾多大學藝術機構耕耘的主要版圖，當代藝術範疇已超越傳統類別的桎梏，視覺與表演時而共冶於舞台之上。目前展覽以臺灣中青輩藝術家為主，給予藝術路 上努力不懈的藝術創作者展覽機會，藝術界人才濟濟，目前回顧三十年個展紀錄中尚 無重複者，近十年以來，每年也規劃展出數位藝術展覽。除了展覽廳之外，基於服務 校園的精神，也將觸角延伸至需要藝術的角落，如文化公園藝術季、臺北市轄、風雲 樓、旺宏館、人社院、台積館。同時也協助辦理校內籌備會議，催化出師生與民眾對空 間的共鳴，並有深刻的互動與對話。"
p4 = "音樂活動豐富多采，通常規劃系列性國內外知名表演團體，例如古典音樂、爵士樂、世界音樂、國樂、跨界表演等系列。駐校音樂家是長期計畫的亮點如蘇顕達音樂家、 黃義方音樂家、何婉甄均有亮麗的展現。間或舉辦音樂舞蹈工作坊如中東鼓、中東肚 皮舞、火舞、爵士樂等工作坊。配合校慶辦理音樂性活動，校慶電玩音樂會也引起大 眾的注目與稱讚。並經常與張昭鼎紀念基金會、台積電、聯電知名業界合作，共創音 樂活動、共享音樂資源。"
p5 = "場地整修發想創意思考辯證，活動包含展演與學習，規劃工作坊、示範演出、專題講座等方向，兼具創意學習、專業知識、實驗精神，提供深入多元的藝術參與機會。以 期開發場地整修創作與應用的能力；展現場地整修在劇場與各種場域演出的應用；連 結場地整修於生活。場地整修活動邀請優質場地整修團隊蒞校示範演出，舉辦專題講 座，與國家兩廳院場館、台中歌劇院、衛武營國家藝術文化中心合作，安排師生聆賞 國際表演團體演出、觀摩交流。"
p6 = "活動練習撫慰人心反映時代，夜貓子電影院自2006年成立，初期便決定從作者論出發，按導演作品年表選映，呈現導演完整的創作脈絡；此外，亦策劃主題性影展與類型 影展，包括科幻影展、林強電影配樂、黃文英影像美術特展等。平均一個月一檔專題 影展，邀請導演蒞臨分享，以及舉辦影像創作工作坊。影展創辦已逾十年，我們所選 映的電影大部分皆已購入清大圖書館館藏，藉由影展的推介與館藏資料庫，培養觀眾 的觀影品味，推動活動練習。並建立部落格與粉絲團，深受大眾的支持與讚賞。"
p7 = "水清木華美好的自然校園中，藝術中心提供生活美學的真摯體驗，凝視展覽廳中的藝術作品、傾聽藝術家親自講解創作理念、聆聽音樂會中流轉的樂章、欣賞一齣戲劇情 緒跟隨著起承轉合、與創作者在工作坊中放鬆肢體感受自我，晚上看場夜貓子電影院 播放之影集，思索人生真諦，漫步校園，走過《葉子》《無聲的對話》或《對弈、對 藝》，沉潛在周遭藝術氛圍，流連其中，驀然回首，三十年光陰倏忽已過。藝術中心 夥伴們永遠懷抱理想，望向未來，繼續締造燦爛藝術斐頁。"

[page_activity]
visual_art = "行政會議"
music = "音樂藝術"
performing_art = "場地整修"
film_art = "活動練習"
abstract = "藝術中心希望透過各種層次的「藝術參與」，營造活潑的社區藝術生活。不管是由我們自行策劃，或與專業單位合作，都以創造藝術社群與清大的互動為主要目標。一方面，藝術中心策劃主辦精彩的藝術活動；另一方面，我們也在校園內參與改造許多藝術空間，如清大合勤廳、教育館藝術空間、陽光走廊、大禮堂等，鼓勵更多元的藝文管道，例如藝術性學生社團、商業團體、藝術基金會等類型的展演，也都能在校園蓬勃發展。"
visual_art_content = "藝術中心目前展覽廳每年度約展出六大檔期，主要以臺灣中青輩藝術家的作品為主要目標，教育館後方的臺北市轄每年度也有數檔展覽， 特別鼓勵較無機會參與商業畫廊體系的藝術家參展。觀眾除了校內教職員生外，附近社區及市區也是主要的欣賞族群。藝術中心規劃每檔展覽（含邀請展與申請展） 展現多元形式與豐富的藝術內容，堅毅執著地介紹當代藝術深度內涵與視野，體現藝術真、善、美的一面，網頁載有展覽論述與相關資料， 期待呈現出藝術家與觀眾都具互動性與意義的行政會議文本。除了展覽廳與臺北市轄之外，校內其他展覽場地尚有陽光走廊，教育館一F空間與人文社會學院藝文空間。"
music_content = "音樂表演節目，以多元化為主，藝術中心為盡到在校園中藝術大使之角色，多方的介紹並邀請不同的演出團體至校園中演出，讓學生近距離就可欣賞到國際級與地方團體的種種表演。多年來，藝術中心所舉辦之音樂表演含括古典音樂，爵士音樂，國樂，流行創作音樂，電影配樂，民族風音樂等各類型音樂演出，並以自由入場形式讓學生，教職員以及新竹地區民眾們可以選擇喜愛的音樂會參加。"
performing_art_content = "<p>藝術中心場地整修展演與學習，以專題方式企劃「workshop」、「示範演出」、「專題講座」三方向，兼具創意學習、專業知識、實驗精神，提供深入多元的藝術參與機會。以期開發場地整修創作與應用的能力；展現場地整修在劇場與各種場域演出的應用；連結場地整修於生活。</p><p>1. Workshop：</p><p>針對校內師生與教職員，企劃藝術教育推廣課程，例如：創意、肢體、聲音、現代舞、默劇、相聲、阿根廷探戈、音樂劇、編劇、排演、劇場技術與管理實務、燈光、音響…等主題，開設場地整修相關工作坊訓練，每次招收 20 位學員，十周的訓練課程，另需參與正式展演呈現學習成果。</p><p>2. 場地整修活動：</p><p>(1) 邀請優質場地整修團隊蒞校示範演出，舉辦專題講座。</p><p>(2) 與國家兩廳院場館、台中歌劇院、衛武營國家藝術文化中心合作，安排師生聆賞國際表演團體演出、觀摩交流。    </p>"
film_art_content = "<p>─ 夜貓子電影院</p><p>夜貓子電影院自2006年成立之初，決定從作者論出發，按導演作品年表選映，呈現導演完整的創作脈絡；此外，亦策劃主題性影展與類型影展，包括科幻影展、林強電影配樂、黃文英影像美術特展等。平均一個月一檔專題影展，邀請導演蒞臨分享，以及舉辦影像創作工作坊。影展創辦已逾十年，我們所選映的電影大部分皆已購入圖書館館藏，藉由影展的推介與館藏資料庫，培養觀眾的觀影品味，推動活動練習。</p><p><a href='http://nightcats.blogspot.tw/'>部落格：http://nightcats.blogspot.tw/</a></p><p><a href='https://www.facebook.com/NTHUNIGHTCATS/'>粉絲團：https://www.facebook.com/NTHUNIGHTCATS/</a></p>"

[page_place]
title = "歷史相片"

  [page_place.zyxel]
  building_name = "日治時期"
  description_1 = "日治時期前身為清大第一講堂，九十二年經合勤科技董事長朱順一博士襄助整建，成為多元的小型藝術表演場地，每年均有超過百場次的租用，成為新竹市內租借收費合理、適合演出、地理位置適中的小型藝術表演廳。"
  description_2 = "九十七年轉由清大藝術中心管理後，陸續推展「設備修換及系統整合」、「休息室整修工程」、「技術操控及藝文服務訓練課程」計畫，現更擴及校內、外藝文講座、室內樂、戲劇、舞蹈、電影播映、社團成果展以及藝術季活動，未來合勤廳將持續提升場地與設備，達到理想的表演需求。"
  floor_plan = "查看平面圖"
  equipment = "設備介紹"
  stage = "1. 舞台資訊"
  lights = "2. 燈光系統"
  sound_system = "3. 音響系統"
  projection = "4. 投影設備"
  other_equipment = "5. 其他器材"
  spectatory = "6. 觀眾席"
  outfield = "7. 外場空間"
  backstage = "8. 後台空間"
  technical_information = "技術資訊、申請借用"
  using_and_charging_standard = "使用與收費標準"
  precautions = "注意事項"
  related_forms = "相關表格"
  management_guidelines = "管理要點"
  facility_application_form = "借用申請表"
  planning_profile = "企劃簡表"
  declaration = "切結書"
  charges = "收費標準"

  [page_place.exhibition_hall]
  building_name = "藝中展覽廳"
  description_1 = "本中心成立於民國七十七年，目前編制為主任一人，講師一人，專任企畫五人，兼任助教與工讀生各數名。現有展覽廳約八十八坪，以活動隔板配合展出品區隔空間，以軌道燈提供照明，必要時有一整排窗戶可提供自然光（或以竹簾與隔板減弱、阻絕自然光）。每年推出六至八個展覽活動，以繪畫作品為主，其他行政會議品為輔。"
  description_2 = "為加深學生對展出品的瞭解，所有展覽原則上都將由本中心規劃製作各項導覽（含文字解說、語音導覽、創作者訪談錄影、藝術史電腦資料庫、及現場人員解說，導覽原則與具體做法見附件一與附件二）。"
  description_3 = "此外，為充分發揮導覽媒體之利用價值，未來將努力與國內其它大學之藝術中心建立合作關係，相互推薦展覽品（附完整導覽媒體）。"
  floor_plan_1 = "查看平面圖一"
  floor_plan_2 = "查看平面圖二"
  opening_time = "開放時間"
  exhibition_time = "展 覽 期 間"
  opening_time_1 = "週 一 ～ 週 五 ： 12:00 - 19:00"
  opening_time_2 = "週 六 ～ 週 日 ： 12:00 - 17:00"
  non_exhibition_period = "非展覽期間"
  not_open_to_public = "不對外開放，但照常辦公。 (含暑假、寒假)"
  equipment = "設備介紹"
  equipment_1 = "1. 電視及DVD錄放影機各一部"
  equipment_2 = "2. 攝影機一台"
  equipment_3 = "3. 音響一台"
  equipment_4 = "4. 單槍投影機一部"

  [page_place.art_workshop]
  building_name = "臺北市轄"
  description = "臺北市轄原址是清大生科院養白老鼠的地方，也養了一隻可做實驗的羊，生命科學院搬離原址後，這個空間就變成洗衣房，還賣過早餐，牆上書寫蛋餅五元。一直有點荒蕪的地方最後成了外工班放打掃用具的倉庫。在劉炯朗校長的時候，藝術中心爭取將它成立為藝術小屋。靈感來自德國的電話亭展覽室，在一個不大的地方，不間斷的有藝術展出，就能活化整體的空間氛圍"
  description_1 = "這個位於清華大學光復中學邊機車道的出入口，量體是由本校【木造社】社員，手工蓋的。【木造社】是一群熱愛「木構造」的年輕人組成的社團，早先以一群清大的畢業生為主，後來有了各行各業的伙伴。臺北市轄是他們利用假日一起動手蓋成。整個屋子沒有用到鐵釘，全為木榫接合。 因此是個實驗品，它沒有鐵釘所以不會生鏽，木構造因此也不需要上漆，十幾年過去了，走進這個小空間，仍能夠嗅吸美國香杉的氣味。"
  description_2 = "藝術工房佔地約21平方公尺，適用於平面作品，立體雕塑，及藝術呈現等，每一學期有個三~四個檔期，適合精緻而小巧的展覽。藝術工房有大面積的玻璃，像是一個立體視窗。對於校園而言是一個小巧可愛的展示空間，即使不走進建築裡，臺北市轄透出的光，也能使經過此處的人，感受到地景的生動與溫暖。"
  description_3 = "2017 年秋季當年承辦本案的黃俊憲建築術師，在清華大學舉辦個展，經過討論，將原始建築結構，增加了一個陽台空間。使原本在懸崖上的建築，在地形落差超過一公尺的情況下，延伸整一個陽台增加臺北市轄與整體空間的協調性。目前臺北市轄已經是一個可以有小型演出的箱型空間，讓清華大學的文藝活動能夠有更多元的發展，超過十年的等待，建築師終究完成了他心中理想的藝術空間。"
  description_4 = "臺北市轄正前方的草地上的【雕塑公園】，則是08級學生給學校的一份禮物，經過大家的手，以拼貼馬賽克完成的雕塑群。連接教育館的一樓的展覽廳、日光走廊以及後方的臺北市轄。位處藝術展覽與創作空間的綠帶上。一般『大人』較少經過這個區域，好像微血管一般，分流到這條路徑的行人，多半是學生。點點空間都帶給行路人微妙的驚喜。這個地方有著奇妙的氛圍，跟紐約蘇活區的形成很像。交錯著藝術創作的活力，與邊陲區域的破落，希望能在這個公園裡，種下溫暖活潑的生命力種籽。"
  description_5 = "【臺北市轄】和【雕塑公園】，成功的證明了清大藝文空間的多樣性，這個精彩的學校，藝術與創作，不只是存在於藝術中心或教室裡。原本荒僻的角落中，因著一屆又一屆的學生，慢慢的琢磨出有意思的傳承。這一帶的發展，和藝術創作的本質相符，不害怕冒險，勇於嘗試，並且不斷追求美好的成果。"



  [footer.mobile]
  opening_time = "諮詢時間: 周一至周五 9:00-12:00；14:00-17:00"
  phone = "電話：886-3-5162222"
  fax = "傳真：886-3-5726819"
  email = "電子信箱：arts@my.nthu.edu.tw"
  address = "地址：30013新竹市光復路二段101號綜合大樓二館1樓"

[page_collect_art]
name = "光復之後"
intro_1 = "前藝術中心主任王小璠教授於2015年召聚大一不分系美術組的學生，成立了【光復之後】，目地是以藝術活動延續不分系藝術類組同學們的藝術創作與向心力，期許他們能為校爭光。並與【歷年榮耀】共同企劃藝術活動和校外團體進行交流。"
intro_2 = "【光復之後】提供不分系藝術類組同學保有創作的空間，並整合藝術中心現有資源，提升清華校園藝術活動的發展。初期就規劃了約20人次的團隊，由林甫珊老師指導教學。定期安排講習、個展、聯展、校外藝術創作行程。希望以人文和藝術產生出影響力。"
intro_3 = "這個充滿實驗性質的團隊，成員間緊密連結，由清華學院大一不分系美術組、創新設計組、和校內熱愛藝術的志願學生組成。平時以工作坊、讀書會，並由學長姐的分享來切磋技法，並有不同主題的聚會凝聚成員們的感情，交流彼此對藝術及生活的想法。在這起初沒有美術相關科系的校園內，【光復之後】以集體的力量發揮藝術創作的效應，即便現在已經有藝術學院，【光復之後】跨領域的特質仍然鮮明。"

[page_collect_music]
name = "歷年榮耀"
intro_1 = "歷年榮耀，曾於2016國家音樂廳，2016阿里山日出音樂會，2010上海世博，2010台北花博，高雄衛武營場地整修中心演出。這樣一支由校園內喜愛古典 樂器演奏各路好手組成的樂團，每學期固定公開演出，為清華大學內一支非音 樂系，非社團，但集合了各領域演奏好手的一個古典樂團體。"
intro_2 = "歷年榮耀並擁有 一支管弦樂團--清華愛樂管弦樂團，團員們人數多時，並會邀請專業級演奏家 與其共同演出，並於各地文化局或演藝廳做公開演奏。清華愛樂管弦樂團是從 原先樂集的室內樂形式改變為管弦樂團，現階段樂團由清大大一不分系音樂組的 同學及校內音樂好手組成，雖是學生樂團，但由於有多位演奏級教師的調教，樂團的爆發力十足，不僅音樂處理細膩，還具備超齡的音樂呈現，多位指導過 的指揮亦嘉許清華愛樂管弦樂團團員驚人的學習力，以及優秀的音樂表現表示 讚許。"
intro_3 = "媒體報導亦曾用 “左手拉琴，右手算微積分”來形容這個左右腦兼用的音 樂團體。歷年榮耀對於支持藝術多元的藝術中心來說，更是藝術中心身為校園 內藝術核心努力開發的一塊音樂園地。"

[navbar]
website_title = "國立清華大學清華學院藝術中心"

  [navbar.navbar_content]
  publication = "出版典藏"
  friends = "清藝之友"
  calendar = "活動月曆"

    [navbar.navbar_content.about_us]
    title = "關於我們"
    history = "中心簡史"
    activity = "活動概述"
    faculty = "組織人員"
    exhibition_venue = "歷史相片"
    chamber_ensemble = "歷年榮耀"
    art_salon = "光復之後"

    [navbar.navbar_content.program]
    title = "展演節目"
    total = "所有類別"
    public_art = "籌備會議"
    visual_art = "行政會議"
    performing_art = "場地整修"
    film_art = "活動練習"

[page_exhibition_detail]
information = "展演資訊"
host = "主辦"
performer = "展演者"
time = "時間"
location = "地點"
ticket_info = "售票資訊"
registration_link = "報名連結"
exhibition_images = "展覽圖片"
detail = "展演介紹"